apiVersion: v1
kind: Service
metadata:
  name: authonline-session-service
  namespace: authonline
  labels:
    app: authonline-session
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: port-5000
    targetPort: 5000
  selector:
    run: authonline-session
  type: ClusterIP